# Generated by Django 2.1.2 on 2019-06-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_user_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rut',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
