# Generated by Django 2.2.dev20180625180104 on 2019-05-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='contrasenia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='contrasenia',
        ),
        migrations.RemoveField(
            model_name='repartidor',
            name='contrasenia',
        ),
    ]
