# Generated by Django 2.2.dev20180625180104 on 2019-05-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medic', '0002_auto_20190508_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicoPostulante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('archivo', models.FileField(upload_to='archivos/Postulante/')),
                ('especialidad', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='medico',
            name='archivo',
            field=models.FileField(upload_to='archivos/Medico/'),
        ),
    ]
