# Generated by Django 2.1.2 on 2019-06-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medic', '0003_medicopostulante_contra'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraLibre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutMedico', models.CharField(max_length=100)),
                ('hora', models.IntegerField()),
                ('fecha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HoraTomada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutMedico', models.CharField(max_length=100)),
                ('rutPaciente', models.CharField(max_length=100)),
                ('hora', models.IntegerField()),
                ('fecha', models.CharField(max_length=100)),
            ],
        ),
    ]
