# Generated by Django 2.1.2 on 2019-06-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medic', '0004_paciente_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.CharField(default='Leve', max_length=100),
        ),
    ]
